# Synthetic host-run OIDC smoke settings. Dot-source in each API/worker/web shell.
# Never use these values or HTTP transport outside local testing.
$env:ENVIRONMENT = 'local'
$env:AUTH_MODE = 'oidc'
$env:OIDC_ISSUER = 'http://localhost:8080/realms/invoiceops'
$env:OIDC_AUDIENCE = 'invoiceops-api'
$env:OIDC_ROLES_CLAIM = 'roles'
$env:DATABASE_URL = 'postgresql+psycopg://invoiceops:invoiceops@127.0.0.1:5432/invoiceops'
$env:REDIS_URL = 'redis://127.0.0.1:6379/0'
$env:S3_ENDPOINT_URL = 'http://127.0.0.1:9000'
$env:S3_ACCESS_KEY_ID = 'invoiceops'
$env:S3_SECRET_ACCESS_KEY = 'invoiceops-local-only'
$env:S3_BUCKET = 'invoice-documents'
$env:WEB_ENVIRONMENT = 'local'
$env:WEB_AUTH_MODE = 'oidc'
$env:WEB_PUBLIC_ORIGIN = 'http://127.0.0.1:3000'
$env:OIDC_CLIENT_ID = 'invoiceops-web'
$env:OIDC_CLIENT_SECRET = 'LocalOnly-Web-Client-NotAProductionSecret'
$env:OIDC_REDIRECT_URI = 'http://127.0.0.1:3000/api/auth/callback'
$env:AUTH_SESSION_REDIS_URL = 'redis://127.0.0.1:6379/1'
$env:INVOICEOPS_API_URL = 'http://127.0.0.1:8000'
